### ISSUE TITLE
Crash in digest_blocks on windows 32-bit

### ISSUE THREAD

**Issue by bridiver** [RustCrypto/utils#989]
We recently started seeing a crash only on win x86 and only in release build configurations. This happens on 0.10 and 0.9 in slightly different places. On 0.9 it's `src\lib.rs:214` and 0.10 it's `src\lib.rs:143`
In both cases it triggers EXCEPTION_ILLEGAL_INSTRUCTION
If we change the debug_asserts to asserts it panics with
```
thread '<unnamed>' panicked at .\../../third_party/rust/block_buffer/v0_10/crate/src/lib.rs:198:13:
assertion failed: false
```
all other platforms/archs (mac, linux, android, win x64, etc..) run fine and win x86 also runs fine when not in release config

**Comment by bridiver** [comment]
In all cases we're calling this from sha2 0.99 (we modified it to work with block-buffer 0.10) https://github.com/RustCrypto/hashes/blob/sha2-v0.9.9/sha2/src/sha512.rs#L32

We are working on updating to sha2 0.10, but it's going to take some time to change things there because the api is different

**Comment by bridiver** [comment]
also relevant is that we're building with chromium which uses its own build system (no cargo) and a nightly rustc snapshot. This started failing after the bump to chromium 120.x which has some rust build changes and a different rustc nightly version, but the code calling this did not change

**Comment by newpavlov** [comment]
Looks like a memory corruption caused by some other `unsafe` code in your project, which got triggered by compiler update. It may be worth to trace your code with debugger to find the exact place where the `pos` field gets filled with garbage.

**Comment by bridiver** [comment]
@newpavlov we took the cpp code out of the equation and were still able to trigger the crash. It also provided a more useful error message https://github.com/brave/brave-core/blob/master/third_party/challenge_bypass_ristretto_ffi/src/lib.rs#L656
```
thread 'main' panicked at .\../../brave/third_party/rust/block_buffer/v0_9/crate/src/lib.rs:214:9:
attempt to subtract with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by bridiver** [comment]
A safe version of the code built using chromium as a pure rust exe does not have the crash so looks like it is something in the ffi code. I'm going to close the issue.

**Comment by bridiver** [comment]
fyi - we have verified that the issue is the alignment change in llvm 18 and this patch fixes it https://github.com/rust-lang/rust/pull/116672
